### ISSUE TITLE
Chinese Version(or in other languages)

### ISSUE THREAD

**Issue by TnTomato** [MichaelCade/90DaysOfDevOps#11]
Hi,
I'm doing some practice on DevOps as well. It's such a hard work because there's several ways of different DevOps around. Different companies have their different details. I'm dedicated to looking for a unique and suitable way of DevOps in my company. So glad to see this repo growing and I'm very willing to practice with you together.
Last but not least, to make it globally, I wonder if there will be a Chinese version(or in other languages) in the future. I can also offer help for translating your DevOps way into Chinese.
Thanks!

**Comment by MichaelCade** [comment]
This is a great idea, I think once I have completed I would love for you to help with the translation.

**Comment by LeslieLeung** [comment]
I can offer help to Chinese translation/proofreading too.

**Comment by stuchilde** [comment]
me to

**Comment by MichaelCade** [comment]
Thank you. My job this week is to go through and proof read then you can do this translation.

**Comment by vjunior1981** [comment]
I can offer for a Brazilian Portuguese version. :)

**Comment by TnTomato** [comment]
Maybe one folder for one language?

**Comment by MichaelCade** [comment]
I think that works with a link from the home readme for specific languages?

**Comment by LeslieLeung** [comment]
@TnTomato @stuchilde See #66 if you are interested.

**Comment by LeslieLeung** [comment]
> I think that works with a link from the home readme for specific languages?

I have created a link in README that links to the Chinese version, see #59

**Comment by ZvanYang** [comment]
i hope i can do this work(Chinese version)

**Comment by akshat5302** [comment]
I'm up for hindi version ✋

**Comment by MichaelCade** [comment]
> I'm up for hindi version ✋

Go for it, we have a few translations happening.

**Comment by akshat5302** [comment]
@stuchilde Could you please guide me on how you converted one for Chinese readme? It will give me a headstart to get started with the Hindi version

**Comment by akshat5302** [comment]
Hi @MichaelCade, could you have any resource on how to do it, so I get a start for doing it

**Comment by manuelver** [comment]
Hi @MichaelCade 

I have already translated into Spanish the .md of the first 5 days and I have left them in this pull request: https://github.com/MichaelCade/90DaysOfDevOps/pull/229

I will continue to translate the next .md because I am interested in the subject. If I see that you find the pull request useful I will keep sending them.

Best regards

**Comment by akshat5302** [comment]
Hey, @LeslieLeung @manuelver It would be great if you could explain me how you translate the readme.md in a particular lang. We could do a meeting in which you can explain how you translated in your lang so that I can work on mine(Hindi version) 
Regards 
Akshat Jain

**Comment by manuelver** [comment]
Hi @akshat5302 

I think it is @MichaelCade who should help you. Anyway, you have [code of conduct](https://github.com/MichaelCade/90DaysOfDevOps/blob/main/CODE_OF_CONDUCT.md) and you can see mine and other contributors' work in the closed issues and pull request.

How I did it was:

1. Create the fork of the entire repository.
2. I prepared my language structure like other translations (New branch and commit for each small job type).
3. Pull request against the main of the original repo from my changes branch.
4. Then I start my translation. For each translated document I create a commit and push on a branch with a push request from the first time. If I make corrections I add it in a descriptive commit. This makes it easier for the owner to review. 
5. Every time the owner merge the pull request branch, I create another numbered branch to have a control of the translations.

The author uses "squash and merge", so you can see each of the numbered branches in [the merged commits from my fork](https://github.com/MichaelCade/90DaysOfDevOps/search?q=manuelver&type=commits).

I hope this is helpful.

Regards

**Comment by akshat5302** [comment]
Thanks @manuelver fir this great answer I will starting working on mine as well

**Comment by MichaelCade** [comment]
Thanks @manuelver (maybe we should add these steps to the contributing file) I think this is a good process for translation.
