### ISSUE TITLE
Day 51: minikube not found error

### ISSUE THREAD

**Issue by PMohanJ** [MichaelCade/90DaysOfDevOps#111]
In day51, after installing minikube through arkade `arkade install minikube` , and when starting minikube `minikube start`, it's rising an error saying minikube not found.

I believe we need to add the arkade bin path to environment variables.

**Comment by saintdle** [comment]
Are you running this on windows or linux?

**Comment by PMohanJ** [comment]
Linux(ubuntu) through wsl from windows.

**Comment by MichaelCade** [comment]
Is this still an issue? Have you tried without using Arkade?

**Comment by PMohanJ** [comment]
No, I've not tried without Arkade. But I found that after installing minikube using arkade, setting up the path of arkade/bin has resolved my issue.

Like this: `export PATH=$PATH:$HOME/.arkade/bin/`

Sorry for late reply, been busy with exams.
