### ISSUE TITLE
In day28.md file a resource like is broken

### ISSUE THREAD

**Issue by PMohanJ** [MichaelCade/90DaysOfDevOps#119]
Hi,

In day28.md file, a resource link `AWS Basics for Beginners - Full Course` which redirects to a Youtube video is broken.
The video isn't available for public in youtube. I hope someone can replace it with suitable one.

If someone knows the exact URL, let me know, I'd like to fix it.

**Comment by PMohanJ** [comment]
I just observed that link continued to exist till day34.md page.

**Comment by MichaelCade** [comment]
Thanks for this, If it is still broken happy to replace or remove via a PR
