### ISSUE TITLE
Let's take a look at the devops scripting framework I wrote

### ISSUE THREAD

**Issue by kasini3000** [MichaelCade/90DaysOfDevOps#13]
hi Michael Cade:
Welcome to the devops scripting framework kasini3000 developed by me.
https://github.com/kasini3000/kasini3000

----
Simple comparison chart
![批量运维工具对比图en9](https://user-images.githubusercontent.com/65390418/148764480-b091c12f-ccdb-4252-9a85-1c24ba43a711.png)

**Comment by MichaelCade** [comment]
Thanks for this will take a look into this and use when I get to the configuration management section.

**Comment by MichaelCade** [comment]
closing stale issue
