### ISSUE TITLE
Grammar & spell check Days 30-90 required

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#133]
I have ran through 1-30 and made edits but need to now do this for the remaining 60 days. 

When this is complete we need to look at how and the best way to publish this as a digital copy and hopefully a physical copy. If anyone has suggestions for this then please comment on this issue. 

The idea is to keep this whole resource free, I have done some research around pandoc and how then can be used to create a combined word document or Google doc for publishing. 

We might also then want to create a branch in time so that no new edits affect the published copy. 

Again any experience in doing this would be greatly appreciated. Deadline is to have a physical option before September 2022.

**Comment by MichaelCade** [comment]
The process I am taking for spelling and grammar is with my local copy I am copying from each day into word and then scanning this against grammarly and the pasting back and pushing to the main repo with all changes.

**Comment by VinayMayavanshi13** [comment]
Okay! Thanks for making this repository.
