### ISSUE TITLE
history command

### ISSUE THREAD

**Issue by rjv1971** [MichaelCade/90DaysOfDevOps#15]
I would add on the history command that with an exclamation point you can run commands from the list. 
for example in your screenshot !3 would execute the clear command again.

Also if the list gets to be too long after a while.... pipe the command to grep if you know (part of) the command you want to use:
"history | grep qfy" will list all commands with "qfy" in it

I would add nano. Not sure what you use as an editor, but good luck learning vi. I know it is all powerful, but the learning curve is steep. 
nano <filename> gets you in, make edits, ctrl-x to close, enter Y to save, done.   

On the ls command: I use ls -als if I want to see a list with permissions etc. in alphabetical order. ls -lart id I want to se them sorted by date/time last used, with the newest on the bottom

**Comment by MichaelCade** [comment]
Great points I will look to add. Thanks for taking the time here. Really helpful and useful. I am going to show nano as you say it’s the easiest. Might touch on VIM but with more links to resources as that’s a different ball game.

**Comment by rjv1971** [comment]
Thanks for doing this. It's really helpful.

**Comment by Scream85** [comment]
On servers to trace back when was a command executed, it can be useful to append the date and time to each command in the history file.

The following system variable controls this behaviour:
HISTTIMEFORMAT="%d-%m-%Y %T "

You can easily add to your bash_profile:
```
echo 'export HISTTIMEFORMAT="%d-%m-%Y %T "' >> ~/.bash_profile
```

So as useful to allow the history file grow bigger:
```
echo 'export HISTSIZE=100000' >> ~/.bash_profile
echo 'export HISTFILESIZE=10000000' >> ~/.bash_profile
```

**Comment by MichaelCade** [comment]
Thank you for your contributions I have added them both to day15.md.
