### ISSUE TITLE
Failed to load plugin schemas

### ISSUE THREAD

**Issue by souravsk** [MichaelCade/90DaysOfDevOps#152]
sovu@sourav-pc:/media/sovu/Data/Devops/terraform$ terraform init

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of kreuzwerker/docker from the dependency lock file
- Using previously-installed kreuzwerker/docker v2.16.0

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
sovu@sourav-pc:/media/sovu/Data/Devops/terraform$ terraform plan
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema:
│ Could not load the schema for provider registry.terraform.io/kreuzwerker/docker:
│ failed to instantiate provider "registry.terraform.io/kreuzwerker/docker" to obtain
│ schema: fork/exec
│ .terraform/providers/registry.terraform.io/kreuzwerker/docker/2.16.0/linux_amd64/terraform-provider-docker_v2.16.0:
│ permission denied..
╵

**Comment by souravsk** [comment]
I'm having this error while the ``terraform plan`` command. I don't know why this error is coming anyone have any solution.

**Comment by MichaelCade** [comment]
I am getting 404 on those registry links. Maybe something has been pulled.

**Comment by MichaelCade** [comment]
Looks like something has changed. https://registry.terraform.io/providers/kreuzwerker/docker/latest

**Comment by souravsk** [comment]
I tried but it didn't work.
