### ISSUE TITLE
Polish Version

### ISSUE THREAD

**Issue by olgachmaj** [MichaelCade/90DaysOfDevOps#155]
Hi! 
I've noticed that this repo is currently in process of being translated into different languages. 
I'd love to start a translation into polish as well if that's of interest.  Thanks :)

**Comment by MichaelCade** [comment]
Love that idea. The trend on doing this has been creating a folder for the translated language and then add to this by PR. Appreciate your efforts.

**Comment by olgachmaj** [comment]
Great, thanks for letting me know! I'll get started on it :)

**Comment by mbrydak** [comment]
Seems like the process is on halt for the past couple of months. I'd be more than happy to contribute and keep it going :)
