### ISSUE TITLE
Story: As a follower, I would love to see AWS Hands-On Scenarios on day34.md

### ISSUE THREAD

**Issue by Codehunter-py** [MichaelCade/90DaysOfDevOps#181]
Hi, 

   I wanted to ask if you could add any links to the AWS Hands-On Scenarios or some additional information about how people could follow same Microsoft Azure Hands-On in the AWS Cloud? 
   As you mentioned at the very beginning about switching between different clouds can make us lost quite easily. It is really true and I am sure some people who are new to cloud concepts can get confused easily. 

Thanks much

**Comment by vishnus17** [comment]
Hi,
I'd recommend understanding the concepts which are being used in the labs first as then you yourself would be able to replicate the same on a different cloud provider as well. 
Most of the terms will be easy for you to understand cross cloud platforms once you get an understanding of the concepts which are being used in the hands-on section. They're just named different even though the concept is very similar. 
Thanks.

**Comment by Codehunter-py** [comment]
Hi,

I think that workshops from AWS would be same as from Azure. I put here link: https://workshops.aws/categories/DevOps

@MichaelCade  would love to know you thoughts about it :)

**Comment by MichaelCade** [comment]
Yes in theory what I ran through on Microsoft Azure could be done on AWS or any cloud based platform. 

I am currently looking at the next 90 days and the topics for this. I will have to look to see if we can include AWS or at least another cloud and some hands on experience for that.

**Comment by vishnus17** [comment]
Ready to help you with that, Michael.

**Comment by MichaelCade** [comment]
@Codehunter-py AWS will be a section covered in the 2023 edition. Watch this space.
