### ISSUE TITLE
Add Docker Desktop installation steps with images 

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#204]
I have been meaning to get this done for a while now but completely forgot, adding an issue to remember to add the steps on https://github.com/MichaelCade/90DaysOfDevOps/blob/main/Days/day43.md so that we show the process for installing Docker Desktop on to our systems. (This should be installed on Windows)

**Comment by zialink** [comment]
Can a random person take on this issue or do you want to do it yourself?

**Comment by MichaelCade** [comment]
I am happy to do it myself but if you have the ability to show this then please do. I will be very grateful for the contribution.
