### ISSUE TITLE
Take existing 90 Days and move to new folder

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#208]
In order to be ready for the next batch of 90 days I need to move existing days into a 2022 folder so that we can then start a new folder for 2023.

**Comment by MichaelCade** [comment]
We will move current readme.md to this 2022 folder and start a new readme.md for 2023 and a better landing readme.md for the overall repository.

**Comment by MichaelCade** [comment]
Also working on a static site to incorporate both years into one page this will enable a future proof in adding more content related to this.

**Comment by MichaelCade** [comment]
> /assign

Already a PR going to some of this work. https://github.com/MichaelCade/90DaysOfDevOps/pull/209

**Comment by Codehunter-py** [comment]
Hi, I have question.

Will there be change notes?  I mean, for example what would be the changes in resource or in configs ? I would really appreciate if there would be some release notes. 

Thanks much

**Comment by MichaelCade** [comment]
@Codehunter-py There will not be changes in configs but the plan is to move all 2022 resources to a new folder, create a new 2023 folder with layout and re format the opening readme to enable the ability to go to each year easily.

**Comment by Lexpeartha** [comment]
> Also working on a static site to incorporate both years into one page this will enable a future proof in adding more content related to this.

Not sure if it is needed, but I would be more than happy to help you with the website!

**Comment by MichaelCade** [comment]
Sounds great have you seen there is now a discord for this that has only just started would be great to talk and see what can be done here.

**Comment by MichaelCade** [comment]
This has been completed
