### ISSUE TITLE
Resource Advise

### ISSUE THREAD

**Issue by hasanozdem1r** [MichaelCade/90DaysOfDevOps#226]
Dear Sir or Madam,

I hope you are doing great. I've seen your nice repository and definitely I love it. 
Thanks for providing this resource to us.
I just wanted to advice this [video ](https://www.youtube.com/watch?v=G_nVMUtaqCk)for the day 1 because of the following things.
1. Resources you have mentioned very nice but this is the most recent one
2. I recently started to follow [TechWorld with Nana](https://www.youtube.com/c/TechWorldwithNana) and her advises very thoughtful
Let me know :)

**Comment by MichaelCade** [comment]
Hey, thanks, I can add this in or you could add this in yourself via a Pull Request. I will leave the issue open until someone has had a chance to update.

**Comment by MichaelCade** [comment]
I have added the resource to day 1 thanks for the feedback.
