### ISSUE TITLE
Use Github Pages for better readability?

### ISSUE THREAD

**Issue by LukeSavefrogs** [MichaelCade/90DaysOfDevOps#243]
This project could use **Github Pages** for the following benefits:
- **cleaner user interface** (no file tree nor Github UI) and 
- **better readability**
- **ease of use**

I think that to start the default settings could do:
![Repository Settings > Pages](https://user-images.githubusercontent.com/33452387/202222001-eeaa9ddb-66ef-4cc9-9e3b-a4d38455d781.png)

**Comment by MichaelCade** [comment]
Thanks Luke. I will take a look. We need to take a look at a bit of the organisation as we get close to the 2023 version where we will add more content and topics.

**Comment by rishabkumar7** [comment]
Opened a PR for docsify implementation that uses GitHub pages
#248

**Comment by LukeSavefrogs** [comment]
> Opened a PR for docsify implementation that uses GitHub pages #248

How can the deployed website be accessed then?

I think it should be displayed on the readme.

**Comment by rishabkumar7** [comment]
@LukeSavefrogs yeah, @MichaelCade will have to setup GitHub pages.

**Comment by MichaelCade** [comment]
Yes sorry I have been out. I will add this to the live stream planned for Friday 2pm GMT

**Comment by MichaelCade** [comment]
Hey, @rishabkumar7 @LukeSavefrogs I have enabled GitHub Pages with the following settings. 



![image](https://user-images.githubusercontent.com/11822323/209701172-f3d1f79e-ae7a-4e15-84e1-c2b7f55c3cdb.png)

**Comment by MichaelCade** [comment]
Very nice [HTTPS - https://www.90daysofdevops.com](https://www.90daysofdevops.com) though not working? I have an SSL wildcard set up here. 

[HTTP - http://www.90daysofdevops.com](http://www.90daysofdevops.com) is working it seems though

**Comment by rishabkumar7** [comment]
Looks like the
<img width="913" alt="Screenshot 2022-12-28 at 8 33 14 AM" src="https://user-images.githubusercontent.com/45825464/209820241-4a34aa07-95d8-4e89-8d1a-a0a787b15f1a.png">
 certificate is working

**Comment by MichaelCade** [comment]
Yes, think this must have been the DNS populating when I made the change. Thank you for your efforts, looks great.

**Comment by LukeSavefrogs** [comment]
Thank you all 🎇
