### ISSUE TITLE
Make the twitter publish message better

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#247]
It would be good to add the commit message to the twitter publish on each PR

**Comment by MichaelCade** [comment]
There is a GitHub action that currently runs when ever there is a PR merged. I would like this GitHub action to include the commit message so twitter can see what has been changed or updated.

**Comment by Abbas-Hussain-Muzammil** [comment]
Ohh... Looking into it and figuring out how can I solve it!

**Comment by MichaelCade** [comment]
I figured this out and you can find the answer in the github action and also in this tweet https://twitter.com/MichaelCade1/status/1606333199180783617?s=20&t=sNAc_XardnO6-wq5w6N9Pw

**Comment by Abbas-Hussain-Muzammil** [comment]
Ohh... nice.
