### ISSUE TITLE
Add meet the crew / contributors for 2023

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#255]
We should create a page where we have a brief bio of the SMEs covering topics for 2023. 

Will require headshots, bio and social links 

@rishabkumar7 Iassume if we do this with another markdown file it will just render with GitHub pages?

**Comment by rishabkumar7** [comment]
Yeah @MichaelCade , also let me know I can create a GitHub Action to create that markdown page `contributors.md` which fetches the contributors automatically and updates the md file on regular basis.

**Comment by MichaelCade** [comment]
I think there should be a list of all contributors over all time and then specifically a highlight of the people contributing the 2023 topics with a little bit about them.

**Comment by rishabkumar7** [comment]
@MichaelCade Let me see, there might be a way to have some content of the file as static and then contributors can be added to the bottom by the GitHub Action

**Comment by Addax101** [comment]
Awesome, I would love to get my hands wet with DevOps for 2023. For contributions count me in.

**Comment by i-Am-GhOsT** [comment]
Amy good first issue to look. I can contribute 😄😄.

**Comment by rishabkumar7** [comment]
@MichaelCade created a PR for fetching and creating contributors.md on #256

**Comment by MichaelCade** [comment]
Completed
