### ISSUE TITLE
Add a link to 2023 website in readme.md file

### ISSUE THREAD

**Issue by akshat5302** [MichaelCade/90DaysOfDevOps#282]
If someone lands on the github page, there is no link to the actual 90 days of devops website. Maybe we should add a link to the website so that people could navigate through the website as well

**Comment by MichaelCade** [comment]
Great point I think we can do this.

**Comment by akshat5302** [comment]
Ok I will work on it and add a link to the website in the readme file

**Comment by kelvinparmar** [comment]
Hello @MichaelCade anyone working in this issue?
If not please let me what I have to do for solving that issue

**Comment by MichaelCade** [comment]
It looks like @akshat is on it

**Comment by akshat5302** [comment]
Yes @MichaelCade I'm going to raise a PR for that as well by today

**Comment by MichaelCade** [comment]
Closed with https://github.com/MichaelCade/90DaysOfDevOps/pull/290
