### ISSUE TITLE
Index Is Missing

### ISSUE THREAD

**Issue by ankurparashar** [MichaelCade/90DaysOfDevOps#303]
Recently when I started 90DaysOfDevOps there was an index page which tells about each day title, recently maintainers are busy in putting lot of flashlights and bringing this repo into limelight instead of restoring the index page.

**Comment by MichaelCade** [comment]
What do you mean by Index? 

We have https://github.com/MichaelCade/90DaysOfDevOps/blob/main/2022.md showing you the list of topics for 2022 

and we have https://github.com/MichaelCade/90DaysOfDevOps/blob/main/2023.md for the list of topics for 2023

Both of these pages can be reached from the main readme.md https://github.com/MichaelCade/90DaysOfDevOps

We have also added GitHub Pages - https://www.90daysofdevops.com/#/

Please let me know what you mean by Index and what was there before regarding Index?

**Comment by ankurparashar** [comment]
thanks, links are accessible now.
