### ISSUE TITLE
Broken link for day 2

### ISSUE THREAD

**Issue by SD-13** [MichaelCade/90DaysOfDevOps#306]
In the 2022 version, the day2 link at the bottom of [this](https://www.90daysofdevops.com/#/2022/Days/day01) page is giving `404 Not found` error. To reproduce just click on `Day 2`.

![Screenshot from 2023-01-25 20-15-52](https://user-images.githubusercontent.com/89520981/214596234-65d26e0c-48d7-47ea-bb89-6745b64f073b.png)

**Comment by SD-13** [comment]
Please have a look @MichaelCade. Thanks,

**Comment by ariyonaty** [comment]
Hiya there, just tacking on to this issue that the same issue is occuring on the [Day 03 page](https://www.90daysofdevops.com/#/2023/day03): 
![image](https://user-images.githubusercontent.com/18715356/218346527-b65bce80-ec42-4bec-a736-a4f03ce668ad.png)

The correct link should be:
```diff
- https://www.90daysofdevops.com/#/day04
+ https://www.90daysofdevops.com/#/2023/day04
```

**Comment by SD-13** [comment]
@ariyonaty It's happening for all the pages

**Comment by MichaelCade** [comment]
Yes my advice is to use the GitHub repository and not the website where all links are working. The website is work in progress

**Comment by FabsMuller** [comment]
@MichaelCade if you create a private repo for the site, you can close here and open there , just as a reminder and improvement. As it has nothing to do with this repo.

**Comment by MichaelCade** [comment]
Not sure I am following, this site is based on the GH_Pages branch so I could go through that and make these changes I guess but that doesn't seem an efficient way? @rishabkumar7 do you have thoughts on this?

**Comment by rishabkumar7** [comment]
@MichaelCade yeah I think that would be nice, to have a seperate branch for the GH_Pages, we don't have that yet, I will work on it

**Comment by MichaelCade** [comment]
Yes we can do that, we would need to consider on each of the days there should be a link to the following day, this will have to differ between the gh_pages branch and main. 

I think on the main branch another thing missing is a link back to the main 2023.md or 2022.md as well, I know a lot of people use this vs the new website.

**Comment by MichaelCade** [comment]
The issue has been resolved with a new branch. 2022 is complete and navigation now works great thanks to @rishabkumar7 for his help there. 

2023 and Translations in progress. 

Closing issue
