### ISSUE TITLE
SSL Certificate

### ISSUE THREAD

**Issue by MichaelCade** [MichaelCade/90DaysOfDevOps#311]
Expired and needs to be renewed

**Comment by jankipmehta** [comment]
The SSL renewal process typically involves generating a new certificate signing request, submitting it to the certificate authority, verifying ownership of the website, and then installing the new SSL certificate on the web server. 

This article has in detailed guide about SSL Renewal steps - [https://sslwiki.org/how-to-renew-ssl-certificate/](https://sslwiki.org/how-to-renew-ssl-certificate/)

**Comment by MichaelCade** [comment]
Thank you this has been completed.
