### ISSUE TITLE
Broken link for The Phoenix Project book found in Day-03

### ISSUE THREAD

**Issue by cristisulighetean** [MichaelCade/90DaysOfDevOps#315]
<img width="811" alt="Screenshot 2023-02-07 at 23 32 17" src="https://user-images.githubusercontent.com/45721851/217370544-ffda376f-2a8b-44b6-8927-9802edbc3c29.png">

**Comment by MichaelCade** [comment]
Thank you this must be due to location. I added the UK link so it works for me in the UK. Will try and find a more global link.

**Comment by FabsMuller** [comment]
The link is working for me now @MichaelCade.

**Comment by MichaelCade** [comment]
Interesting I didn't change anything

**Comment by FabsMuller** [comment]
> Interesting I didn't change anything

The link is point to amazon.com, maybe it was an amazon.co.uk problem. But it's working fine. Can be closed, for sure.
