### ISSUE TITLE
Kubescape-Day 32

### ISSUE THREAD

**Issue by Obasoro** [MichaelCade/90DaysOfDevOps#336]
@MichaelCade, kubescape not installing Apple M1, though I have opened an Issue with them on their github page

```
==> Downloading https://formulae.brew.sh/api/formula.json
##O=#  #                                                                      
==> Downloading https://formulae.brew.sh/api/cask.json
##O=#  #                                                                      
Error: kubescape has been disabled because it does not build!

```

**Comment by MichaelCade** [comment]
Please keep us up to date of their reply. I know some tools I used in 2022 are not available for M1 or M2 architectures.

**Comment by Obasoro** [comment]
@MichaelCade, Kubescape has fixed the bug. On M1 and M2 you can install it.  

`https://github.com/kubescape/kubescape`

**Comment by MichaelCade** [comment]
Thanks for this, did you already submit a PR to update the days where this should be to help others with this?

**Comment by Obasoro** [comment]
No, I did not submit a PR on this. I would do that. Regards

**Comment by MichaelCade** [comment]
I thought I saw @Obasoro comment with a fix but must have been another issue they stumbled across. Good job I didn't close.

**Comment by MichaelCade** [comment]
Are we complete on this issue?

**Comment by Obasoro** [comment]
So far @MichaelCade No issue on this after Kubescape fixed it for MacOs M1 and M2 chip users.

**Comment by MichaelCade** [comment]
I am good to close then?

**Comment by Obasoro** [comment]
Yes
