### ISSUE TITLE
[HTTP Network Protocol] Typo in 250, the correct value is 200

### ISSUE THREAD

**Issue by ad3n** [MichaelCade/90DaysOfDevOps#34]
Typo in 250, the correct value is 200

https://github.com/MichaelCade/90DaysOfDevOps/blob/main/Days/day23.md

**Comment by MichaelCade** [comment]
Please provide a resource. I was understanding that HTTP on success is 200. For SMTP it would be 250.

**Comment by ad3n** [comment]
<img width="772" alt="Screen Shot 2022-02-10 at 08 59 20" src="https://user-images.githubusercontent.com/7464920/153322890-01a44953-af88-4d27-9c31-bf60bf06cd16.png">
Yes sure but you have typo here

**Comment by MichaelCade** [comment]
Thanks I will have a search and fix the image. Thanks for getting back to me.

**Comment by MichaelCade** [comment]
This has been resolved, sorry it took so long.
