### ISSUE TITLE
[Suggestion] DAY 14 : virtualbox and vagrant doens't work well on Appli Sillicon (M1 macbook)

### ISSUE THREAD

**Issue by roeniss** [MichaelCade/90DaysOfDevOps#365]
I tried a few ways to make it working, but failed.

Instead, I succeeded to boot ubuntu with `multipass` : https://blog.ipspace.net/2022/02/ubuntu-mac-m1.html

I want to add this alternative virtual environment on DAY 14 note, if you allow it.

**Comment by MichaelCade** [comment]
Happy to add, would you like to contribute via a PR and add the alternative method to the day

**Comment by MichaelCade** [comment]
Merged with https://github.com/MichaelCade/90DaysOfDevOps/pull/366
