### ISSUE TITLE
How to I customize my terminal like MichaelCade's terminal?

### ISSUE THREAD

**Issue by vineethsankre** [MichaelCade/90DaysOfDevOps#370]
### Discussed in https://github.com/MichaelCade/90DaysOfDevOps/discussions/368

<div type='discussions-op-text'>

<sup>Originally posted by **vineethsankre** March 20, 2023</sup>
I'm currently using a Windows terminal and wsl2. Also, bash shell in wsl2
Reference: ![image](https://user-images.githubusercontent.com/113631587/226267300-9279649c-ded1-47bb-848c-e538233dd116.png)
</div>

**Comment by MichaelCade** [comment]
I walk through the steps here. A big part of the customisation is ZSH and the Dracula theme. This will work on WSL2 https://youtu.be/jeEslAtHfKc

**Comment by MichaelCade** [comment]
Awesome, join the discord and let us know how it goes.
