### ISSUE TITLE
GtiHub action workflow for this repo

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [MichaelCade/90DaysOfDevOps#415]
Greetings for the day! I would like to add some GitHub actions to this repository to save time for maintainers. Specifically, I would like to add actions for the following scenarios:

When someone opens an issue
When someone closes an issue
When someone opens a pull request
When someone closes a pull request
When a maintainer merges a pull request

I would also like to set up an action for the above.

**Comment by MichaelCade** [comment]
Hey we have some of these but feel free to contribute, how would these actions help the repo and the community?

**Comment by Vikash-8090-Yadav** [comment]
> Hey we have some of these but feel free to contribute, how would these actions help the repo and the community?

I saw but  in this repo there is only 3 github actions that is for -
Twitter post, Blog and One is for when some raised the pr. first time. 
My contribution involves - 
When someone opens an issue
When someone closes an issue
`When someone open or closes the issue then the random message will be displayed to the opener as well as closer`
When a maintainer merges a pull request
`When pr merge then it will display welcome and  thanking message to opener` 


and if I found more I will add  those also  
---
Let me know about your input on this .
