### ISSUE TITLE
https://www.90daysofdevops.com/#/2023 link leads to 2022 content

### ISSUE THREAD

**Issue by Pickacho** [MichaelCade/90DaysOfDevOps#420]
![image](https://github.com/MichaelCade/90DaysOfDevOps/assets/40912416/fc5be3b2-beae-4d7d-b913-cf3cdb0c552b)

**Comment by MichaelCade** [comment]
Yes 2023 has not been added to the website yet.

**Comment by rishabkumar7** [comment]
@MichaelCade Are we good to add 2023 content to the web platform?

**Comment by MichaelCade** [comment]
Yes let's go. Thank you.
