### ISSUE TITLE
Day 14 / VAGRANTFILE Command / Powershell Error

### ISSUE THREAD

**Issue by Phlashlol** [MichaelCade/90DaysOfDevOps#43]
Removing "mb" from the following line in the Vagrantfile fixed a powershell-error for me. 

from
>  v.customize ["modifyvm", :id, "--vram", "128mb"] 

to 
> v.customize ["modifyvm", :id, "--vram", "128"]

If this error is only experienced by me, please remove and mark as closed. Thank you very much for your great guide so far.

Error Message for reference: 
> A customization command failed:
> 
> ["modifyvm", :id, "--vram", "128mb"]
> 
> The following error was experienced:
> 
> #<Vagrant::Errors::VBoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
> for controlling VirtualBox. The command and stderr is shown below.
> 
> Command: ["modifyvm", "(Id here)", "--vram", "128mb"]

**Comment by MichaelCade** [comment]
Thanks for this and could be useful to keep open here. Could also add as a PR to Day 14.
