### ISSUE TITLE
Resources Link not found on YT.

### ISSUE THREAD

**Issue by abhay-raj19** [MichaelCade/90DaysOfDevOps#444]
While i was going through the day 28 (cloud days)

Resources link for youtube (AWS Basics for Beginners - Full Course) was not found on youtube.

Docs image:
<img width="960" alt="image" src="https://github.com/MichaelCade/90DaysOfDevOps/assets/96302417/488275a8-21cf-4205-a504-d31225154b1a">

Youtube image:
<img width="960" alt="image" src="https://github.com/MichaelCade/90DaysOfDevOps/assets/96302417/c0322579-af91-40c8-9b85-6ba5c83d385f">
 Will change it to the best rated AWS basic for beginners course on youtube. 
 
 Can change it to  freecodecamp YT lecture.
 https://youtu.be/SOTamWNgDKc?si=Gf-BdjRvkOV7-mgh
 
or
https://youtu.be/k1RI5locZE4?si=yd5LKX8OKu3KlY8u
 
or
https://youtu.be/r4YIdn2eTm4?si=tAt7JDa_wKseckLe

**Comment by abhay-raj19** [comment]
Pls assign me so that I can work on it and resolve it ASAP. @MichaelCade

**Comment by MichaelCade** [comment]
Please submit a PR with the removal or update @abhay-raj19
