### ISSUE TITLE
No content on day 40 and 41

### ISSUE THREAD

**Issue by 1belini** [MichaelCade/90DaysOfDevOps#467]
Hello, there is no content to follow on days 40 and 41 as the next image shows:

![image](https://github.com/MichaelCade/90DaysOfDevOps/assets/100674901/75df4189-d6b3-4500-ae7d-709df905f5c2)

**Comment by MichaelCade** [comment]
It has not been completed up till now. It does need to be completed with two more hands on scenarios. 

I just need to find time to make these happen.
