### ISSUE TITLE
Youtube video for cloud resource AWS Basics for Beginners - Full Course is not available

### ISSUE THREAD

**Issue by dylanlarrivee** [MichaelCade/90DaysOfDevOps#51]
Link for the [AWS Basics for Beginners - Full Course](https://www.youtube.com/watch?v=ulprqHHWlng&t=5352s) is private and not available for viewing. Is there another link that is recommended to be used? Really great content in here but I am using AWS at my current job so hoping to stick with what is a bit more familiar to me.

Link: https://www.youtube.com/watch?v=ulprqHHWlng&t=5352s

**Comment by MichaelCade** [comment]
Oh no. Let me take a look tomorrow and see which one this was, it must have been taken down.

**Comment by dylanlarrivee** [comment]
Thanks! Any chance you would be doing a cloud section on AWS like you didn't for Azure?

**Comment by MichaelCade** [comment]
Absolutely. Not finished and my intentions is to keep this repository going

**Comment by saintdle** [comment]
Propose this one from Digital Ocean
https://www.youtube.com/watch?v=zlmrkM-IvtI

**Comment by MichaelCade** [comment]
This has been added
