### ISSUE TITLE
translate to traditional chinese version

### ISSUE THREAD

**Issue by subineru** [MichaelCade/90DaysOfDevOps#78]
I'm interested in translating for traditional chinese version.
so that more people would have an opportunity to read this repository.
if anyone are interested to join this or help me to proofread the content, please comment in below.
I'll also update the process in here.

- [ ] README (WIP)
- [x] Day35 
- [ ] Day36 (WIP)
- [x] Day37
- [ ] Day38(WIP)

**Comment by wenchaoh997** [comment]
Hi subineru, i am interested in this repo, and just begin to learn something. 
If it is possible, I am willing to join your translation work. But i am a beginner on many things XD.
