### ISSUE TITLE
Spanish Version

### ISSUE THREAD

**Issue by CalvitoUy** [MichaelCade/90DaysOfDevOps#83]
Hi Michael;
I would like to be able to do the translation into Spanish for my community, where we still have many members who are not 100% fluent in English, do you agree?
Do you prefer that I do it in my own fork or do you prefer that I create a folder to do it inside your repository?

**Comment by MichaelCade** [comment]
Hey, firstly thanks for wanting to help here. 

We have been starting this translation to Chinese you can see an additional folder where this is taking place. 

I think it would be good to add a Spanish folder for the translation and link in the readme? 

Happy to discuss

**Comment by CalvitoUy** [comment]
Hi Michael;
I start the Spanish translation, if you want to add Spanish folder and link in the readme is good for me, I just want contribute with the spanish speakers community.



________________________________
De: Michael Cade ***@***.***>
Enviado: domingo, 24 de abril de 2022 4:25
Para: MichaelCade/90DaysOfDevOps ***@***.***>
Cc: Alejandro Martinez ***@***.***>; Author ***@***.***>
Asunto: Re: [MichaelCade/90DaysOfDevOps] Spanish Version (Issue #83)


Hey, firstly thanks for wanting to help here.

We have been starting this translation to Chinese you can see an additional folder where this is taking place.

I think it would be good to add a Spanish folder for the translation and link in the readme?

Happy to discuss

**Comment by saintdle** [comment]
You can fork this repo and create a spanish folder yourself, and start to add the files, then create a PR to sync back.

**Comment by tsen73** [comment]
There are some problems that I am facing in this feature you can check [Custom Web design Utah](https://fluid22.com/) project and kindly help me to fix this problem.

**Comment by nelbren** [comment]
Hello @CalvitoUy! How is the translation going? It could also help in the effort.
