### ISSUE TITLE
Day 5 : CI / CD topic interchange needed

### ISSUE THREAD

**Issue by vrp-314** [MichaelCade/90DaysOfDevOps#84]
https://github.com/MichaelCade/90DaysOfDevOps/blob/main/Days/day05.md#continuous-delivery - needs to be https://github.com/MichaelCade/90DaysOfDevOps/blob/main/Days/day05.md#continuous-integration and vice versa

Below correction would be required

Continuous Integration = Plan > Code > Build > Test
Continuous Delivery = Release

**Comment by saintdle** [comment]
#93 - issue should be resolved in this PR once the final edits have been made

**Comment by kelvinparmar** [comment]
Hello anyone working on this issue? otherwise I want to work on this issue and explain what I have to do

**Comment by MichaelCade** [comment]
We have the PR noted above still open just waiting on a response and if there are any edits before closing and merging.
