### ISSUE TITLE
Website Creation Idea

### ISSUE THREAD

**Issue by Rafat97** [MichaelCade/90DaysOfDevOps#90]
Hi, This is awesome repository.  It's helps a lot people who are interested in DevOps. Thanks to all the contributor, maintainer, owner to creating this awesome GitHub repo.

Have you any plane to create a website?

**Comment by MichaelCade** [comment]
Thanks, I have the domain 90DaysOfDevOps.com

**Comment by Rafat97** [comment]
Was you planed any web UI layout?

**Comment by Rafat97** [comment]
> Thanks, I have the domain 90DaysOfDevOps.com

Sounds good. 

Was you planed any web UI layout or you planed to use any opensource docs maker like `docsifyjs/docsify`,  `mkdocs-material` etc?

**Comment by MichaelCade** [comment]
I was looking at Gitdocs but have some other plans first before pushing into this. The first step is to proof read everything and create an ebook of the repo and possibly some physical copies.

**Comment by MichaelCade** [comment]
Also https://www.gitbook.com/

**Comment by Rafat97** [comment]
If you want to use `gitbook`. I think we can use this types of working flow. 

If anything push on main branch -> a action will trigger -> automatically deployed the gitbook

**Comment by Rafat97** [comment]
By, mistake I close this issue.

**Comment by MichaelCade** [comment]
Thanks for this.
